version: 'v1'

services:
 warehouse:
   image: postgres
   container_name: warehouse
   environment:
     POSTGRES_USER: ${WAREHOUSE_USER}
     POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD}
     POSTGRES_DB: ${WAREHOUSE_DB}
   volumes:
     - ./containers/warehouse:/docker-entrypoint-initdb.d
   healthcheck:
     test: [ "CMD", "pg_isready", "-U", "${WAREHOUSE_USER}" ]
     interval: 5s
     retries: 5
   restart: always
   ports:
     - "5432:5432"
   networks:
     - sde_network

 loader:
   image: spoteng
   container_name: spoteng
   build:
     context: ./containers/loader/
   volumes:
     - ./:/opt/sde
   depends_on:
     warehouse:
       condition: service_healthy
   environment:
     WAREHOUSE_USER: ${WAREHOUSE_USER}
     WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD}
     WAREHOUSE_DB: ${WAREHOUSE_DB}
     WAREHOUSE_HOST: ${WAREHOUSE_HOST}
     WARREHOUSE_PORT: ${WAREHOUSE_PORT}
     SPOTIFY_CLIENT: ${SPOTIFY_CLIENT}
     SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
   networks:
     - sde_network

networks:
 sde_network:
   name: sde_network
